"""add videos, video_snapshots and video_outliers

Revision ID: 98891c70184c
Revises: cb87bac12255
Create Date: 2026-09-21 09:15:43.537878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98891c70184c'
down_revision: Union[str, Sequence[str], None] = 'cb87bac12255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id')
    )
    op.create_index('ix_videos_channel_id_published_at', 'videos', ['channel_id', 'published_at'], unique=False)
    op.create_table('video_outliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('baseline_views', sa.Numeric(), nullable=True),
    sa.Column('outlier_ratio', sa.Numeric(), nullable=True),
    sa.Column('recency_weight', sa.Numeric(), nullable=True),
    sa.Column('outlier_score', sa.Numeric(), nullable=True),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_outliers_video_id_calculated_at', 'video_outliers', ['video_id', 'calculated_at'], unique=False)
    op.create_table('video_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('like_count', sa.BigInteger(), nullable=True),
    sa.Column('comment_count', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_snapshots_video_id_collected_at', 'video_snapshots', ['video_id', 'collected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_snapshots_video_id_collected_at', table_name='video_snapshots')
    op.drop_table('video_snapshots')
    op.drop_index('ix_video_outliers_video_id_calculated_at', table_name='video_outliers')
    op.drop_table('video_outliers')
    op.drop_index('ix_videos_channel_id_published_at', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
