"""add last_discovery_at to niches

Revision ID: cb87bac12255
Revises: 6f8b76b4d4b2
Create Date: 2026-09-03 15:00:17.826592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb87bac12255'
down_revision: Union[str, Sequence[str], None] = '6f8b76b4d4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('niches', sa.Column('last_discovery_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('niches', 'last_discovery_at')
    # ### end Alembic commands ###
