"""add markets and opportunities

Revision ID: d3a78eba34c9
Revises: a4c3bf5b5695
Create Date: 2026-09-21 10:00:24.068149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3a78eba34c9'
down_revision: Union[str, Sequence[str], None] = 'a4c3bf5b5695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.Text(), nullable=False),
    sa.Column('language_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('rpm_estimado', sa.Numeric(), nullable=True),
    sa.Column('falantes_estimados', sa.BigInteger(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('angulo', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='mapeada', nullable=False),
    sa.Column('volume_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('concorrencia_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_opportunities_score', 'opportunities', ['opportunity_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_opportunities_score', table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('markets')
    # ### end Alembic commands ###
